### ISSUE TITLE
Comment on OMB Source Code Policy [Request for discussion] How OMB should measure impact of its pilot #118

### ISSUE THREAD

**Issue by wslack** [18F/tts-public-comments#14]
Originally [posted](https://github.com/WhiteHouse/source-code-policy/issues/118) by @konklone. Formatting not preserved here.

_(I’m Eric, an engineer at [18F](https://18f.gsa.gov/), an office in the [U.S. General Services Administration](http://www.gsa.gov/) (GSA) that provides in-house digital services consulting for the federal government. I’m commenting on behalf of 18F; we’re an [open source team](https://18f.gsa.gov/2014/07/29/18f-an-open-source-team/) and happy to share our thoughts and experiences. This comment represents only the views of 18F, not necessarily those of the GSA or its Chief Information Officer.)_

The [proposed policy says in section 5.1](https://sourcecode.cio.gov/OSS/):

> Within 120 days of the publication of this policy, OMB shall develop metrics to assess the impact of the pilot program. No later than two years after the publication date of this policy, OMB shall consider whether to issue a subsequent policy to continue, modify, eliminate, or expand the pilot program.

It'd be helpful to hear more from OMB about how they want to evaluate the success of the pilot program. Quantitative metrics for many things are going to be challenging. For example:
- Is it about measuring whether procuring open source affected code quality? This is very difficult to measure in any automated or quantitative way, and for comparing to closed source projects it will require going past various authentication walls and inside different agency systems.
- Is it about measuring whether procuring open source affected the cost of projects? This will require some real effort at coming up with the costs of custom software development, and separating those aspects of the contracts that procured them from any other sort of work included in the contract. Contracts often include custom software development as just one piece. This is something agencies and OMB can make a real effort to track centrally, and the [IT Dashboard](https://itdashboard.gov) might make a good tie-in effort.
- Is it about measuring where procuring open source led to greater reusability among agencies, or by the public? In this case, it's worth understanding that while open source is a necessary precondition to reusability by the public, and (we believe) a practical precondition of wide reuse among agencies -- just releasing open source code isn’t sufficient to support robust reuse. Open sourcing a monolithic agency-specific code base won't lead to reuse. You also need to modularize your code, and identify parts of it that are reusable and separate it cleanly from your other work. As a concrete example, [18F designed analytics.usa.gov](https://18f.gsa.gov/2015/03/19/how-we-built-analytics-usa-gov/) with reuse in mind by splitting the project into two repositories: a [GSA-specific front-end](https://github.com/18F/analytics.usa.gov), and a [general-purpose analytics command-line tool](https://github.com/18F/analytics-reporter). If we had not split these out, we would not see the same level of contributor interest and reuse that we have. 18F also [works on publicizing its open source projects](https://github.com/WhiteHouse/source-code-policy/issues/94) to support reuse, to improve the chances of people hearing about them. Additionally, "reuse" is broader than just tracking raw code reuse -- showing how an agency accomplished a particular task can lead to other agencies adopting similar approaches (perhaps in other programming languages more well-supported in their environment), even if the code wasn't literally reused.

To truly measure the effects of the pilot, OMB will need to spend time looking at the context, code, and cost that are specific to any projects they wish to analyze. It's not something OMB can do by scanning through the public internet, or through the software inventories OMB is asking agencies to produce. The best thing OMB might do is to commission a report, by GSA or a cross-agency team or something, that is empowered (and funded) to work with agencies directly to evaluate various situations that OMB's open source pilot helped to empower.

These are our initial reactions, and we'd love to hear from others about the approach OMB might take to evaluation metrics.

**Comment by konklone** [comment]
Updated mine with the original Markdown.
